# Generated by Django 3.2.7 on 2021-09-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
