# Generated by Django 3.2.7 on 2021-09-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clients_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
