# Generated by Django 3.2.7 on 2021-09-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clients_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
    ]
