# Generated by Django 3.2.7 on 2021-09-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_indexbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_placement', models.CharField(help_text='Example: index page - banner', max_length=255)),
                ('surtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='IndexBanner',
        ),
    ]
