# Generated by Django 3.2.7 on 2021-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210916_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statictext',
            name='image',
        ),
        migrations.AddField(
            model_name='statictext',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='statictext',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
