# Generated by Django 3.2.7 on 2021-09-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
