# Generated by Django 3.2.7 on 2021-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_websitesettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictext',
            name='bullet_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
