# Generated by Django 3.2.7 on 2021-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_statictext_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_company', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('socials', models.ManyToManyField(blank=True, limit_choices_to={'is_company': False}, related_name='socials', to='core.SocialAccount')),
            ],
        ),
    ]
