# Generated by Django 3.2.7 on 2021-09-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210918_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategories',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
