# Generated by Django 3.2.7 on 2021-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_projectcategories_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
