# Generated by Django 3.2.7 on 2021-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='promotion_video_image',
            field=models.ImageField(default=False, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
