# Generated by Django 3.2.7 on 2021-09-29 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
