# Generated by Django 3.2.7 on 2021-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210929_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
