# Generated by Django 3.2.7 on 2021-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_websitesettings_address_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='address_link',
            field=models.CharField(max_length=255),
        ),
    ]
