# Generated by Django 3.2.7 on 2021-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_websitesettings_address_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='addresses/')),
                ('type_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='+994', max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
