# Generated by Django 3.2.7 on 2021-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_addesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='address_link',
            field=models.CharField(max_length=255),
        ),
    ]
