# Generated by Django 3.2.7 on 2021-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210929_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='facebook_address',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='instagram_address',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
