# Generated by Django 3.2.7 on 2021-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20211001_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='whatsapp_address',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
