# Generated by Django 3.2.7 on 2022-02-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20211013_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='about_us_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='signature_about_page',
            field=models.ImageField(blank=True, null=True, upload_to='about-page/signature/'),
        ),
    ]
