# Generated by Django 3.2.7 on 2022-02-24 08:00

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20220224_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='signature_about_page',
            field=models.ImageField(blank=True, null=True, upload_to=core.tools.get_about_page_signature),
        ),
    ]
