# Generated by Django 3.2.7 on 2022-02-24 08:19

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_websitesettings_signature_about_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=core.tools.get_about_page_signature)),
                ('author_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('author_position', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='signature_about_page',
        ),
    ]
