# Generated by Django 3.2.7 on 2022-02-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_bulletpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='static_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets_points', to='core.statictext'),
        ),
    ]
