# Generated by Django 3.2.7 on 2022-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_bulletpoint_static_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='title_az',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='title_en',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
