# Generated by Django 3.2.7 on 2022-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20220224_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
