# Generated by Django 3.2.7 on 2022-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictext',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statictext',
            name='subtitle_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statictext',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
